
experiment_name: lorenz_train
dataset_type: "FIMSDEpDataset" #FIMSDEpDataset,FIMPOODEDataset,FIMCompartmentDataset

integration:
  method: "EulerMaruyama"
  # time_step: 0.1
  time_length: 10
  steps_per_dt: 20
  num_steps: 128
  num_paths: 50
  num_locations: 1024
  chunk_size: 5000 # generate at one time so many realizations (to filter Nans)
  reject_threshold: 100
  stochastic: true

locations:
  type: random_cube

train:
  - name: Lorenz63System
    data_bulk_name: lorenz__train
    redo: &redo false
    num_realizations: &num_realizations_train 15000
    observed_dimension: null
    drift_params:
      sigma:
        distribution: "uniform"
        min: 10.0
        max: 20.0
      beta:
        distribution: "uniform"
        min: 2.5
        max: 5.0
      rho:
        distribution: "uniform"
        min: 28.0
        max: 40.0
    diffusion_params:
      constant_value: 1.0
      dimensions: 3
    initial_state:
      distribution: "normal"
      mean: 0.0
      std_dev: 1.0
      activation: "sigmoid"


test:
  - name: Lorenz63System
    data_bulk_name: lorenz_test
    redo: *redo
    num_realizations: &num_realizations_test 1500
    observed_dimension: null
    drift_params:
      sigma:
        distribution: "uniform"
        min: 10.0
        max: 20.0
      beta:
        distribution: "uniform"
        min: 2.5
        max: 5.0
      rho:
        distribution: "uniform"
        min: 28.0
        max: 40.0
    diffusion_params:
      constant_value: 1.0
      dimensions: 3
    initial_state:
      distribution: "normal"
      mean: 0.0
      std_dev: 1.0
      activation: "sigmoid"


validation:
  - name: Lorenz63System
    data_bulk_name: lorenz_validation
    redo: *redo
    num_realizations: &num_realizations_val 1500
    observed_dimension: null
    drift_params:
      sigma:
        distribution: "uniform"
        min: 10.0
        max: 20.0
      beta:
        distribution: "uniform"
        min: 2.5
        max: 5.0
      rho:
        distribution: "uniform"
        min: 28.0
        max: 40.0
    diffusion_params:
      constant_value: 1.0
      dimensions: 3
    initial_state:
      distribution: "normal"
      mean: 0.0
      std_dev: 1.0
      activation: "sigmoid"
