
experiment_name: polynomials_drift_deg_3_diffusion_deg_0_1_path_50_paths_equivalent
dataset_type: "FIMSDEpDataset" #FIMSDEpDataset,FIMPOODEDataset,FIMCompartmentDataset

integration:
  method: "EulerMaruyama"
  # time_step: 0.1
  time_length: 500
  steps_per_dt: 20
  num_steps: 6400
  num_paths: 1
  num_locations: 1024
  chunk_size: 40000 # generate at one time so many realizations (to filter Nans)
  reject_threshold: 100
  stochastic: true

locations:
  type: regular_cube
  extension_perc: 0.3

train:
  - name: Polynomials
    data_bulk_name: train_deg_1
    num_realizations: &num_realizations_train 10000
    observed_dimension: null
    state_dim: 1
    redo: &redo false
    enforce_positivity: &enforce_positivity "abs"
    max_degree_drift: &max_degree_drift 3
    max_degree_diffusion: &max_degree_diffusion 0
    drift_params: &drift_params
      distribution:
        name: normal
        std: 1
      degree_survival_rate: 0.5
      monomials_survival_distribution:
        name: uniform
        min: 0.25
        max: 1
      scale: &scale
        sample_per_dimension: false
        distribution: "uniform"
        min: 0.0
        max: 2.0
    diffusion_params: &diffusion_params
      distribution:
        name: normal
        std: 1.0
      degree_survival_rate: 0.5
      monomials_survival_distribution:
        name: uniform
        min: 0.1
        max: 1.0
      scale: *scale
    initial_state: &initial_state
      # distribution: "uniform"
      # min: -1
      # max: 1
      # activation: null
      distribution: "normal"
      mean: 0.0
      std_dev: 1.0
      activation: null

  - name: Polynomials
    data_bulk_name: train_deg_2
    num_realizations: *num_realizations_train
    observed_dimension: null
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    state_dim: 2
    redo: *redo
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state

  - name: Polynomials
    data_bulk_name: train_deg_3
    num_realizations: *num_realizations_train
    observed_dimension: null
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    state_dim: 3
    redo: *redo
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state

test:
  - name: Polynomials
    data_bulk_name: test_deg_1
    num_realizations: &num_realizations_test 1000
    observed_dimension: null
    state_dim: 1
    redo: *redo
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state

  - name: Polynomials
    data_bulk_name: test_deg_2
    num_realizations: *num_realizations_test
    observed_dimension: null
    state_dim: 2
    redo: *redo
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state

  - name: Polynomials
    data_bulk_name: test_deg_3
    num_realizations: *num_realizations_test
    observed_dimension: null
    state_dim: 3
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    redo: *redo
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state

validation:
  - name: Polynomials
    data_bulk_name: val_deg_1
    num_realizations: &num_realizations_validation 1000
    observed_dimension: null
    state_dim: 1
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    redo: *redo
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state

  - name: Polynomials
    data_bulk_name: val_deg_2
    num_realizations: *num_realizations_validation
    observed_dimension: null
    state_dim: 2
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    redo: *redo
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state

  - name: Polynomials
    data_bulk_name: val_deg_3
    num_realizations: *num_realizations_validation
    observed_dimension: null
    enforce_positivity: *enforce_positivity
    max_degree_drift: *max_degree_drift
    max_degree_diffusion: *max_degree_diffusion
    state_dim: 3
    redo: *redo
    drift_params: *drift_params
    diffusion_params: *diffusion_params
    initial_state: *initial_state
